import type { StorybookConfig } from '@storybook/react-vite';

const config: StorybookConfig = {
  // The fixture is a separate git repo generated by scripts/generate-fixture.mjs.
  stories: ['../fixture/src/**/*.stories.@(ts|tsx)'],
  addons: ['storybook-addon-component-contributors'],
  framework: '@storybook/react-vite',
  core: { disableTelemetry: true },
};

export default config;
